/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "db_driver.h"
#include "db_serial.h"
#include "db_json.h"
#include "yoc_serialport.h"
#include<stdio.h>
#include<stdlib.h>
#include<unistd.h>
#include<string.h>
#include "ev_config.h"
#include "vbox_api.h"

#define VBOX_TYPE   911


static jstring JSON_stringfy(JNIEnv *env,cJSON *root,char *text)
{
    jstring msg;
    text = cJSON_Print(root);
    cJSON_Delete(root);
    if(text != NULL){
        msg = (*env)->NewStringUTF(env,text);
        free(text);
    }
    else{
        msg = (*env)->NewStringUTF(env,"{\"EV_vbox\":{\"EV_type\":9999}}");
    }
    return msg;
}

/*
 * Class:     com_easivend_evprotocol_VboxProtocol
 * Method:    EV_portRegister
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_easivend_evprotocol_VboxProtocol_VboxReadMsg
  (JNIEnv *env, jclass cls, jint fd, jint timeout)
{
    jstring msg;
    char *text = NULL;
    cJSON *root,*entry;
    VBOX_MSG *vmsg;

    vmsg = VBOX_readMsg(fd,(uint32)timeout);
    root=cJSON_CreateObject();
    entry = cJSON_CreateObject();
    cJSON_AddItemToObject(root, JSON_HEAD,entry);
    cJSON_AddNumberToObject(entry,JSON_TYPE,VBOX_TYPE);

    if(vmsg == NULL){
        cJSON_AddNumberToObject(entry,"mt",VBOX_TIMEOUT);
    }
    else{
        cJSON_AddNumberToObject(entry,"port",vmsg->port);
        if(vmsg->res == 0){
            cJSON_AddNumberToObject(entry,"mt",VBOX_TIMEOUT);
        }
        else if(vmsg->res == 1){
            cJSON_AddNumberToObject(entry,"mt",vmsg->mt);
            cJSON_AddNumberToObject(entry,"sn",vmsg->sn);
            cJSON_AddNumberToObject(entry,"ver",vmsg->ver);
            cJSON_AddNumberToObject(entry,"F7",vmsg->F7);
        }
        else{
            cJSON_AddNumberToObject(entry,"mt",VBOX_DATA_ERROR);
        }
    }

    msg = JSON_stringfy(env,root,text);

    return msg;
}


JNIEXPORT jstring JNICALL Java_com_easivend_evprotocol_VboxProtocol_VboxSendAck
  (JNIEnv *env, jclass cls, jint fd)
{
    jstring msg;
    char *text = NULL;
    cJSON *root,*entry;
    int res;
    res = VBOX_sendAck(fd);
    root=cJSON_CreateObject();
    entry = cJSON_CreateObject();
    cJSON_AddItemToObject(root, JSON_HEAD,entry);
    cJSON_AddNumberToObject(entry,JSON_TYPE,VBOX_TYPE);
    cJSON_AddNumberToObject(entry,"send_result",res);
    msg = JSON_stringfy(env,root,text);
    return msg;
}


JNIEXPORT jstring JNICALL Java_com_easivend_evprotocol_VboxProtocol_VboxGetSetup
  (JNIEnv *env, jclass cls, jint fd)
{
    jstring msg;
    char *text = NULL;
    cJSON *root,*entry;
    int res;
    res = VBOX_getSetup(fd);
    root=   cJSON_CreateObject();
    entry = cJSON_CreateObject();
    cJSON_AddItemToObject(root, JSON_HEAD,entry);
    cJSON_AddNumberToObject(entry,JSON_TYPE,VBOX_TYPE);
    cJSON_AddNumberToObject(entry,"send_result",res);
    msg = JSON_stringfy(env,root,text);
    return msg;
}



