/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_easivend_evprotocol_VboxProtocol */

#ifndef _Included_com_easivend_evprotocol_VboxProtocol
#define _Included_com_easivend_evprotocol_VboxProtocol
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif
#endif
